#
# Experimental Dockerfile for SoapyRemote
#
# From: https://hub.docker.com/r/marcelmaatkamp/soapy-remote/dockerfile
#
# Build with:
#     docker build --network host --rm --tag=soapy-remote:latest .
#
# Run with:
#     docker run -d -p 1234:1234 --net=host --privileged -v /dev/bus:/dev/bus -v /var/run/dbus:/var/run/dbus --name=soapy-remote soapy-remote
#
# Prerequisites:
#
# On the host you might need to blacklist modules related to SDR.
# E.g.: For RSP1A, Create: /etc/modprobe.d/blacklist-msi2500.conf with:
#
#     # Blacklist msi2500 so Docker container can use the device
#     blacklist sdr_msi3101
#     blacklist msi001
#     blacklist msi2500
#
# License:
#
# By running this, you automatically agree to the EULA contained in the
# SDRplay driver (https://www.sdrplay.com/downloads/).
#

FROM ubuntu:latest

ENV DEBIAN_FRONTEND=noninteractive
ENV LD_LIBRARY_PATH=/lib:/usr/lib:/usr/local/lib

# avahi-daemon \
# libavahi-client-dev \
# libboost-all-dev \

RUN apt-get update \
  && apt-get install -y \
    wget \
    udev \
    git \
    cmake \
    g++ \
    libgmp-dev \
    swig \
    python3-numpy \
    python3-mako \
    python3-sphinx \
    python3-lxml \
    python3-yaml \
    python3-pyqt5 \
    doxygen \
    libfftw3-dev \
    libcomedi-dev \
    libsdl1.2-dev \
    libgsl-dev \
    libqwt-qt5-dev \
    libqt5opengl5-dev \
    liblog4cpp5-dev \
    libzmq3-dev \
    gnuradio \
    gnuradio-dev

RUN wget http://www.sdrplay.com/software/SDRplay_RSP_API-Linux-2.13.1.run \
  && chmod +x *.run \
  && ./SDRplay_RSP_API-Linux-2.13.1.run --noexec --keep
WORKDIR package
RUN sed -i -n '1,4p;16,$p' install_lib.sh \
  && sed -i 's/sudo / /g' install_lib.sh \
  && ./install_lib.sh
WORKDIR ../

#RUN git clone git://git.osmocom.org/gr-osmosdr
#WORKDIR gr-osmosdr
#WORKDIR build
#RUN cmake .. -DCMAKE_BUILD_TYPE=Release \
#  && make \
#  && make install
#WORKDIR ../../

RUN git clone https://github.com/pothosware/SoapySDR.git
WORKDIR SoapySDR
WORKDIR build
RUN cmake .. -DCMAKE_BUILD_TYPE=Release \
  && make \
  && make install
WORKDIR ../../

#RUN git clone https://github.com/pothosware/SoapyOsmo.git
#WORKDIR SoapyOsmo
#WORKDIR build
#RUN cmake .. -DCMAKE_BUILD_TYPE=Release \
#  && make \
#  && make install
#WORKDIR ../../

RUN git clone https://github.com/pothosware/SoapySDRPlay.git
WORKDIR SoapySDRPlay
WORKDIR build
RUN cmake .. -DCMAKE_BUILD_TYPE=Release \
  && make \
  && make install
WORKDIR ../../

# RUN git clone https://github.com/pothosware/SoapyRTLSDR.git
# WORKDIR SoapyRTLSDR
# WORKDIR build
# RUN cmake .. -DCMAKE_BUILD_TYPE=Release \
#   && make \
#   && make install
# WORKDIR ../../

RUN git clone https://github.com/pothosware/SoapyRemote.git
WORKDIR SoapyRemote
WORKDIR build
RUN cmake .. -DCMAKE_BUILD_TYPE=Release \
  && make \
  && make install

#EXPOSE 55132
#EXPOSE 1900/udp
EXPOSE 1234

CMD SoapySDRServer --bind="0.0.0.0:1234"
